### ISSUE TITLE
Enchantment not being removed.

### ISSUE THREAD

**Issue by aWitch-Doctor** [Daniel12321/AdventureMMO#27]
In the latest version 2.0.6, if you use an unenchanted item for gigadrill or mad miner the efficiency 5 enchantment added does not get removed. There are no errors in the log for this. It also doesn't set the durability back to what it was before the ability was used.

**Comment by Daniel12321** [comment]
Testing this in 1 hour

**Comment by Daniel12321** [comment]
It seems to work fine for me. Do you have any mods on the server?

**Comment by ToolMan2k** [comment]
I can confirm that version 2.0.6 does not restore enchanted items, at least on a modded server. Could be it a conflict? Possibly. Is it OK to send our modlist so you can check where is the problem?

**Comment by Daniel12321** [comment]
Sure, ill take a look at it.

**Comment by Daniel12321** [comment]
I just noticed that the durability not going back is because i didnt actually code it in... Well thats silly of me.

**Comment by Daniel12321** [comment]
I just released a new version, v2.0.7, that **might** fix all these issues, but im not 100% sure. It will at least fix the durability issue. Can you guys test it? Thanks 👍 :)

**Comment by aWitch-Doctor** [comment]
I have loaded the 2.0.7 for api 5 but the issue with the enchant is still happening.

have an unenchanted pick axe, then use mad miner. While using mad miner efficiency 5 enchant is added to the pick axe. After mad miner is done it should put the pick axe back to being unenchanted but it doesn't. it leaves the efficiency 5 enchant on it. Same thing happens for giga drill.

Current plugins are:
GriefPrevention
WorldEdit
AurionsVoteListener
Nucleus
Lottery
SignEditor
Total Economy
PlayerShopsRPG
AdventureMMO
LuckPerms
ProjectPortals
NuVotifier
Nucleus Mixins
VoxelSniper
Prism

**Comment by yepidoodles** [comment]
Happening to me too on v2.0.7

Server info: http://www.dragontechmc.com/wiki/m/39190744/page/Everlands_2.3


EDIT: I added Tinkers' tools to my config, the extra enchants on those work like normal but then stay like the others, however they remove upon relogging.

**Comment by ToolMan2k** [comment]
Tried it yet again, but it's still keeping the enchantments.
Here's a list of mods & plugins I have, if you need so. I am using SpongeForge, so that could be a factor :
**Forge mods**
![adventuremmo modlist](https://cloud.githubusercontent.com/assets/26819563/24799985/27a0e686-1b6c-11e7-86eb-1bef68f29286.PNG)
**Sponge plugins**
![adventuremmo modlist 2](https://cloud.githubusercontent.com/assets/26819563/24799986/27a31c6c-1b6c-11e7-8d60-0f00a2d8a1d8.PNG)

**Comment by MadByteDE** [comment]
Any progress with this issue?
I tested a bit and found that already enchanted items recover to their previous state but not enchanted items get stuck with the unbreakable state and the efficiency enchantment. The "Super" prefix seems to get removed from an unenchanted item.

**Comment by Daniel12321** [comment]
I have been testing a lot, with modded servers and normale servers, and it is causes by some certain mods. I dont know why, it makes no sence, and according to all laws of physics it should just not happen.

**Comment by MadByteDE** [comment]
I set up a test server without any mods (just spongeforge-1.10.2-2281-5.2.0-BETA-2274 and adventuremmo_2.0.7) and I got the problem as well. 
I had a look at the code but (as an complete java noob) could't find a problem. I thought it might help to log each step of ItemUtils:restoreSuperTool and SuperToolData:restore and see where the code doesn't get called or where variables don't get passed properly. 
Hope you find the problem :)

**Comment by Daniel12321** [comment]
I did this. All parts of the code got called as they should. I think it has something to do with ghosting of items, as the tools turn back to normal when relogging.

**Comment by Daniel12321** [comment]
I also found out this only happens on 1.10 servers, not 1.11

**Comment by MadByteDE** [comment]
Okay, my last idea would be to destroy the enchanted SuperTool and replace it with another tool you create based on the SuperToolData of the original item. But this sound more like a work around then a fix... :/

**Comment by Wissi** [comment]
We can report same issue. Efficiency 5 enchant will NOT remove after effect has worn off.
Full mod pack: https://minecraft.curseforge.com/projects/minecolonies-testpack/relations/dependencies

If you need more info to help, let us know.

**Comment by tannertechnology** [comment]
I have this bug as well, playing Resonant Rise 4 on sponge 1.10.2-2281-5.2.0-BETA-2341

The plugins I have are luckperms and nucleus
@Daniel12321 If it helps I can get you details to setup this modpack and let you join my server for testing

**Comment by lolmetimbers** [comment]
Ugh...this issue is still here and totally breaks the skills abilities.

2.0.7 for api 5 on 1.10.2

Please fix/update
